// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Entity;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(StafiContext))]
    [Migration("20240411211408_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Entity.Stafi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gjinia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mbiemri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("nrPersonal")
                        .HasColumnType("bigint");

                    b.Property<long?>("nrTelefonit")
                        .HasColumnType("bigint");

                    b.Property<string>("orari")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("stafis");
                });
#pragma warning restore 612, 618
        }
    }
}
